### ISSUE TITLE
Ideas for future project improvements (IDF-8066) 

### ISSUE THREAD

**Issue by tomassebestik** [espressif/idf-python-wheels#13]
Hi, 
here are some notes/ideas for future project improvements:

- maybe use python images `python:3.8`, `python:3.9` instead of one image with PyEnv
    - I'm not sure if you then install RUST on that image for things like `cryptography`.
    - if installing too many add-ons to a base image like `python:3.8` would be too tedious (it will run in every job), then maybe we can create custom images in the https://github.com/espressif/github-esp-dockerfiles project (maybe a custom image for each python?)
    
- The scheduled pipeline should also build:
    - requirements from this `tools/requirements` directory of the `esp-idf` project: https://github.com/espressif/esp-idf/tree/master/tools/requirements
    - automatically for all python versions, all architectures, all missing wheels upload to https://dl.espressif.com/pypi/
    
- create a workflow with only "Drop AWS cache + update index.html", only on `workflow dispatch` (manual run)
    - this is useful for cases where a wheels needs to be quickly added manually (e.g. using CyberDuck) to AWS and we only need to rebuild the cache and index

**Comment by dobairoland** [comment]
Thanks @tomassebestik for the suggestions. We will consider them all. See also the linked issue number for future discussion.

As for the third item, there is an ad-hoc-wheel action which should address that. The aim is to avoid manually built wheels. We had several times issues with incorrect wheels which broke all CI pipelines. So I'd rather not support that. If there is anything missing for you in that action then we could address that instead.
